%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /home/piter/Desktop/Data Cleaning/HW4/Diabetes.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2014/04/14 19:26:27

%% Import the data
data = xlsread('/home/piter/Desktop/Data Cleaning/HW4/Diabetes.xlsx','Sheet1');

%% Allocate imported array to column variable names
VarName1 = data(:,1);
VarName2 = data(:,2);
VarName3 = data(:,3);
VarName4 = data(:,4);
VarName5 = data(:,5);
VarName6 = data(:,6);
VarName7 = data(:,7);
VarName8 = data(:,8);
VarName9 = data(:,9);
VarName10 = data(:,10);

%% Clear temporary variables
clearvars data raw;